// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTFSR2nLXXbjyUIYHeANzIWDgVnwPKYzI',
    appId: '1:481899236249:web:98dd0263beac4d501fa108',
    messagingSenderId: '481899236249',
    projectId: 'my-coolest-project-test',
    authDomain: 'my-coolest-project-test.firebaseapp.com',
    storageBucket: 'my-coolest-project-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrTN0xbGE56qgOeTESB5tJKybwmM0KMg',
    appId: '1:481899236249:android:dd61301b38bda77e1fa108',
    messagingSenderId: '481899236249',
    projectId: 'my-coolest-project-test',
    storageBucket: 'my-coolest-project-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChQ0jKEVveVChX6hHANgJkInm_kqW08mk',
    appId: '1:481899236249:ios:4718f37a2bf543df1fa108',
    messagingSenderId: '481899236249',
    projectId: 'my-coolest-project-test',
    storageBucket: 'my-coolest-project-test.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChQ0jKEVveVChX6hHANgJkInm_kqW08mk',
    appId: '1:481899236249:ios:4718f37a2bf543df1fa108',
    messagingSenderId: '481899236249',
    projectId: 'my-coolest-project-test',
    storageBucket: 'my-coolest-project-test.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTFSR2nLXXbjyUIYHeANzIWDgVnwPKYzI',
    appId: '1:481899236249:web:a900bfa7e825439a1fa108',
    messagingSenderId: '481899236249',
    projectId: 'my-coolest-project-test',
    authDomain: 'my-coolest-project-test.firebaseapp.com',
    storageBucket: 'my-coolest-project-test.appspot.com',
  );
}
